version: '3.1'

volumes:
  prometheus_data: {}
  alertmanager_data: {}
  grafana_data: {}

services:
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - ./rules:/etc/prometheus/rules/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: always

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml
      - alertmanager_data:/alertmanager
    command: 
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path="/alertmanager"'
    ports:
      - 9093:9093
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - .env

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    restart: always

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server

  redis-exporter:
    image: bitnami/redis-exporter:latest
    restart: always
    ports:
      - 9120:9120
    command:
      - '--include-system-metrics=true'
      - '--web.listen-address=0.0.0.0:9120'
      - '--redis.addr='
      
  custom_exporter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9130:9130
    restart: always