global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

rule_files:
  - /etc/prometheus/rules/*.yml
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
  - job_name: 'nodes'
    scrape_interval: 10s
    static_configs:
      - targets:
          - "localhost:9090"
          - "node-exporter:9100"

  - job_name: 'redis'
    metrics_path: /scrape
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: redis-exporter:9120
      target_label: __address__
    static_configs:
    - labels:
        service: random_redis
      targets:
      - redis://redis:6379

  - job_name: 'custom_exporter'
    scrape_interval: 10s
    static_configs:
      - targets:
          - "custom_exporter:9130"