---
- name: Adding User
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid }}"
    comment: "{{ item.fullname }}"
    shell: /bin/bash
    state: "{{ item.state | default('present') }}"
  with_items: "{{ dev_team }}"

- name: Update the authorized_keys file
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  when: item.get('state', 'present') == 'present'
  with_items: "{{ dev_team }}"

- name: Assign sudo role to the admin users
  copy:
    content: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/99-{{ item.username }}"
    mode: 0440
    owner: root
    group: root
  when: item.type is defined and item.type == 'admin' and item.get('state', 'present') == 'present'
  with_items: "{{ dev_team }}"
