plugin: amazon.aws.aws_ec2
regions: # update with the regions used in your AWS account
  - us-west-1
  - us-west-2
keyed_groups:
  # each prefix below becomes a dynamic inventory list used by Ansible
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type
  - key: placement.region
    prefix: aws_region
